name: Hackathon App - Build & Run Docker

on:
  workflow_dispatch:  # Manual run
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t hackathon_app .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --env-file .env hackathon_app
          sleep 15
          docker logs $(docker ps -q --filter ancestor=hackathon_app)
