name: Build and Run Docker App

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  docker-build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from GitHub Secrets
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env

      - name: Build Docker image
        run: docker build -t hackathon_app .

      - name: Run container detached
        run: docker run -d --name hackathon_container -p 8000:8000 --env-file .env hackathon_app

      - name: Stream logs (Cloudflare URL will appear here)
        run: docker logs -f hackathon_container &

      - name: Wait for tunnel to initialize
        run: sleep 120
